_S(c_tan	,"tg"		, 1)
_S(c_ctan	,"ctg"		, 1)
_S(c_sin	,"sin"		, 1)
_S(c_cos	,"cos"		, 1)
_S(c_ln		,"ln"		, 1)
_S(c_log	,"log"		, 2)
_S(c_sqrt	,"sqrt"		, 1)
_S(c_asin	,"arcsin"	, 1)
_S(c_acos	,"arccos"	, 1)
_S(c_atan	,"arctg"	, 1)
_S(c_exp	,"exp"		, 1)
_S(c_pow	,"pow"		, 2)
_S(c_fac	,"fac"		, 1)

_NUM(13)