_S(d_tg		,"tg"		, 1)
_S(d_ctg	,"ctg"		, 1)
_S(d_sin	,"sin"		, 1)
_S(d_cos	,"cos"		, 1)
_S(d_ln		,"ln"		, 1)
_S(d_log	,"log"		, 2)
_S(d_sqrt	,"sqrt"		, 1)
_S(d_arcsin	,"arcsin"	, 1)
_S(d_arccos	,"arccos"	, 1)
_S(d_arctg	,"arctg"	, 1)
_S(d_exp	,"exp"		, 1)
_S(d_pow	,"pow"		, 2)
//_S(d_fac	,"fac"		, 1)

_NUM(12)