--READ UNCOMMITTED

--Потерянные изменения

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
SELECT city_name FROM city WHERE city_id = 108
UPDATE city SET city_name = 'Ufa' WHERE city_id = 108
COMMIT

--Грязное чтение

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
update city SET city_name = 'Ufa' WHERE city_id = 108
ROLLBACK

--READ COMMITTED

--Грязное чтение

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
update city SET city_name = 'Ufa' WHERE city_id = 108
ROLLBACK

--Неповторяющееся чтение

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
update city SET city_name = 'Ufa' WHERE city_id = 108
COMMIT

--REPEATABLE READ

--Неповторяющеея чтение

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
UPDATE city SET city_name = 'Ufa' WHERE city_id = 108
COMMIT

--Фантом

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
INSERT INTO City VALUES(111,'Orel')
COMMIT

--SERIALIZABLE

--Фантом

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
INSERT INTO City VALUES(111,'Orel')
COMMIT