--READ UNCOMMITTED

--Потерянные изменения

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
SELECT city_name FROM city WHERE city_id = 108
UPDATE city SET city_name = 'Pskov' WHERE city_id = 108
COMMIT

--Грязное чтение

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
SELECT * FROM city WHERE city_id = 108
COMMIT

--READ COMMITTED

--Грязное чтение

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
SELECT * FROM city WHERE city_id = 108
COMMIT

--Неповторяющееся чтение

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
SELECT * FROM city WHERE city_id = 108
COMMIT

--REPEATABLE READ

--Неповторяющееся чтение

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
SELECT * FROM city WHERE city_id = 108
COMMIT

--Фантом

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
SELECT * FROM city
COMMIT

--SERIALIZABLE

--Фантом

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
SELECT * FROM city
COMMIT
