-- 1
-- READ UNCOMMITTED

-- LOST CHANGES

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
SELECT city.name FROM city WHERE city_id = 10
UPDATE city SET city.name = 'Ufa' WHERE city_id = 10
COMMIT

-- DIRTY READ

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
update city SET city.name = 'Ufa' WHERE city_id = 10
ROLLBACK

-- 2
-- READ COMMITTED
-- DIRTY READ

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
update city SET city.name = 'New York' WHERE city_id = 10
ROLLBACK

-- NON-REPEATABLE READ

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
update city SET city.name = 'Ufa' WHERE city_id = 10
COMMIT

-- 3
-- REPEATABLE READ
print @@TRANCOUNT
-- NON-REPEATABLE READ

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
UPDATE city SET city.name = 'New york' WHERE city_id = 10
COMMIT

-- PHANTOM

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
UPDATE city SET city.name = 'New york' WHERE city_id = 11
COMMIT

--SERIALIZABLE

--PHANTOM

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
UPDATE city SET city.name = 'New york' WHERE city_id = 12
COMMIT

-- DEAD LOCK

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
UPDATE city SET city.name = 'Second' where city_id = 2
SELECT * FROM city
COMMIT
