-- 1
-- READ UNCOMMITTED

-- LOST CHANGES


-- SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
-- BEGIN TRANSACTION
-- SELECT city.name FROM city WHERE city_id = 10
-- UPDATE city SET city.name = 'Kaliningrad' WHERE city_id = 10;
-- COMMIT


SELECT * FROM city

-- DIRTY READ

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
SELECT * FROM city WHERE city_id = 10
COMMIT

-- 2
-- READ COMMITTED

-- DIRTY READ

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
SELECT * FROM city WHERE city_id = 10
COMMIT

-- NON-REPEATABLE READ

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
SELECT * FROM city WHERE city_id = 10
COMMIT

-- 3
-- REPEATABLE READ

print @@TRANCOUNT
-- NON-REPEATABLE READ

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
SELECT * FROM city WHERE city_id = 10
COMMIT

-- PHANTOM

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
SELECT * FROM city where city.name like '%York%'
COMMIT


--SERIALIZABLE

--PHANTOM

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
SELECT * FROM city where city.name like '%York%'
COMMIT

-- DEAD LOCK

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
UPDATE city SET city.name = 'First' where city_id = 1
SELECT * FROM city
COMMIT

-- EXTRA DEAD LOCK

SELECT * FROM city

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
UPDATE city SET city.name = 'Third' where city_id = 3;
UPDATE city SET city.name = 'Third' where city_id = 4;
SELECT * FROM CITY
COMMIT

