#!/bin/bash
# echo "\documentclass[20pt]{article} \begin{document} \pagestyle{empty} \[" $1 "\]\end{document}" > temp.tex
echo "\documentclass{article} \pagestyle{empty} \usepackage[paperwidth=200.5in,paperheight=100in]{geometry} \usepackage{amsmath} \usepackage{graphicx} \newcommand*{\Scale}[2][4]{\scalebox{#1}{\ensuremath{#2}}} \begin{document} \begin{equation} \LARGE \Scale[6]{ " $1 " }\nonumber \end{equation} \end{document}" > temp.tex
# echo "\documentclass{article} \pagestyle{empty} \usepackage{amsmath} \usepackage{graphicx} \usepackage{breqn} \begin{document} \scalebox{3}{ \$\$   " $1 " \$\$} \end{document}" > temp.tex

pdflatex temp.tex
pdfcrop --margins 30 temp.pdf temp.pdf.out
gs -sDEVICE=ps2write -dNOCACHE -sOutputFile=nofont-Myfile.ps -q -dbatch -dNOPAUSE temp.pdf.out -c quit
# rm temp.pdf
# rm temp.tex
rm temp.aux
rm temp.log
rm temp.pdf.out
convert nofont-Myfile.ps pic.png
rm nofont-Myfile.ps


