#!/bin/bash

#	Converting input formula to .png format
#
#	Version 1.0


echo "\documentclass{article} \pagestyle{empty} \usepackage[paperwidth=200.5in,paperheight=100in]{geometry} \usepackage{amsmath} \usepackage{graphicx} \newcommand*{\Scale}[2][4]{\scalebox{#1}{\ensuremath{#2}}} \begin{document} \begin{equation} \LARGE \Scale[6]{ " $1 " }\nonumber \end{equation} \end{document}" > temp.tex

pdflatex -interaction nonstopmode -halt-on-error -file-line-error temp.tex
pdfcrop --margins 30 temp.pdf temp.pdf.out
gs -sDEVICE=ps2write -dNOCACHE -sOutputFile=nofont-Myfile.ps -q -dbatch -dNOPAUSE temp.pdf.out -c quit
# rm temp.pdf
# rm temp.tex
rm temp.aux
rm temp.log
rm temp.pdf.out
convert nofont-Myfile.ps pic.png
rm nofont-Myfile.ps
