#!/bin/bash
# 
# This is initial script for creating initial software pack installed on 
# Ubuntu laptop
#
# Sergey Ivanychev
#
# v 1.0

sudo apt-get update
sudo apt-get install git
git config --global push.default simple
git config user.name "Sergey Ivanychev"
git config user.email "sergeyivanychev@gmail.com"


cd ~/
mkdir code
cd code
git clone https://github.com/ruzovvo/Laundry.git
git clone https://github.com/ivanychev/os-degradation.git
git clone https://github.com/ivanychev/learning.git

echo "Downloading GetDeb and PlayDeb" && wget http://archive.getdeb.net/install_deb/getdeb-repository_0.1-1~getdeb1_all.deb http://archive.getdeb.net/install_deb/playdeb_0.3-1~getdeb1_all.deb && echo "Installing GetDeb" && sudo dpkg -i getdeb-repository_0.1-1~getdeb1_all.deb && echo "Installing PlayDeb" && sudo dpkg -i playdeb_0.3-1~getdeb1_all.deb && echo "Deleting Downloads" && rm -f getdeb-repository_0.1-1~getdeb1_all.deb && rm -f playdeb_0.3-1~getdeb1_all.deb

sudo add-apt-repository -y ppa:videolan/stable-daily

sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp

sudo add-apt-repository -y ppa:gnome3-team/gnome3

sudo add-apt-repository -y ppa:webupd8team/java

sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager

sudo add-apt-repository -y ppa:transmissionbt/ppa

sudo add-apt-repository ppa:webupd8team/sublime-text-3

wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 

sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E

sudo sh -c 'echo "deb http://linux.dropbox.com/ubuntu/ utopic main" >> /etc/apt/sources.list.d/dropbox.list' 

sudo add-apt-repository ppa:linrunner/tlp

sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade

sudo apt-get install vlc sublime-text-installer google-chrome-stable

sudo apt-get install\
synaptic\
gimp\
gimp-data\
gimp-plugin-registry\
gimp-data-extras\
y-ppa-manager\
bleachbit\
oracle-jdk7-installer\
oracle-java9-installer\
unace\
unrar\
p7zip-full\
p7zip-rar\
sharutils\
rar\
uudeview\
mpack\
arj\
cabextract\
flac\
faac\
faad\
sox\
vorbis-tools\
id3v2\
mpg321\
mpg123\
libflac++6\
icedax\
lame\
libjpeg-progs\
ubuntu-restricted-extras\
terminator\
vlc\
git\
clang-3.5\
banshee\
texlive-full\
r-base\
dropbox\
wireshark\
vim\
valgrind\
cscope\
exuberant-ctags\
doxygen\
exuberant-ctags\
cmake\
biber\
openssh-server\
fail2ban\
x11vnc\
xvnc4viewer\
xzdec

sudo apt-get autoremove
sudo apt-get clean
